# Site settings
title: "RoadTripp Adventures"
description: "Documenting our family road trips and adventures across the country. Join us as we explore new places, create memories, and share our journey with you."
author: "RoadTrippers"
email: priyaaank@gmail.com

# GitHub Pages / Production settings
url: "https://priyaaank.github.io" # Change this to your GitHub username
baseurl: "/roadtripp" # Change this to your repository name
repository: "priyaaank/roadtripp" # Change this to your GitHub username/repoa

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/New_York # Change to your timezone

# Collections
collections:
  trips:
    output: true
    permalink: /:collection/:name/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - docker-compose.yml
  - LOCAL_SETUP.md
  - demo.html

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# SEO settings
defaults:
  - scope:
      path: ""
      type: "trips"
    values:
      layout: "trip"
      author: "Your Family Name"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Family Name"
  - scope:
      path: ""
    values:
      image: "/assets/images/social-share.jpg" # Create this for social sharing 