# Site settings
title: "RoadTripp Adventures"
description: "Documenting our family trips. Mostly to revisit these memories when we are older and forgetful. But also to share with those who may find information helpful"
author: "Roadtripp.in"
email: priyaaank@gmail.com

# GitHub Pages / Production settings
url: "https://roadtripp.in" # Your custom domain
baseurl: "" # Empty for apex domain
repository: "priyaaank/roadtripp" # Change this to your GitHub username/repoa

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/New_York # Change to your timezone

# Collections
collections:
  trips:
    output: true
    permalink: /:collection/:name/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - docker-compose.yml
  - LOCAL_SETUP.md
  - demo.html

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# Analytics
google_analytics: G-LMJ14P8LF8

# SEO settings
defaults:
  - scope:
      path: ""
      type: "trips"
    values:
      layout: "trip"
      author: "Roadtrippers"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Roadtrippers"
  - scope:
      path: ""
    values:
      image: "/assets/images/social-share.jpg" # Create this for social sharing 