services:
  jekyll:
    image: ruby:3.1-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
      - "35729:35729"
    command: >
      sh -c "
        apk add --no-cache build-base &&
        gem install jekyll bundler &&
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --livereload
      "
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true 